backend:
  name: git-gateway
  branch: main

media_folder: 'public/images/uploads' # Folder where user uploaded files should go
public_folder: '/images/uploads'

collections: # A list of collections the CMS should be able to edit
  - name: 'sections' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Sections' # Used in the UI, ie.: "New Post"
    files:
      - label: 'About Section'
        name: 'about'
        file: 'src/cms/about.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: text }
          - { label: Picture, name: picture, widget: image }
          - { label: Linkedin, name: linkedin, widget: string }
          - { label: Resume, name: resume, widget: string }
  - name: 'experiences'
    label: 'Experiences'
    folder: 'src/cms/experiences' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: true
    fields: # The fields each document in this collection have
      - { label: 'Company', name: 'company', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'text' }
      - { label: 'Picture', name: 'picture', widget: 'image' }
      - { label: 'Start', name: 'start', widget: 'datetime' }
      - { label: 'End', name: 'end', widget: 'datetime', default: '' }

    
